

server :
  port: 9191

spring:
  application:
    name: payment-service
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root123



eureka :
  client :
      register-with-eureka : true
      fetch-registry: true
      service-url :
        defaultZone: http://localhost:8761/eureka

      instance :
       hostname : localhost